version: '3.9'

services:
  explorer:
    build:
      dockerfile: Dockerfile
      context: ./psw-be
      target: final
    restart: on-failure
    networks:
      - database
    ports:
      - "9000:80"
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: super
      DATABASE_USER: postgres
      DATABASE_SCHEMA: explorer
    depends_on:
      - database
  database:
    image: postgres:16
    restart: always
    networks:
      - database
    environment:
      POSTGRES_PASSWORD: super
      POSTGRES_USER: postgres
      POSTGRES_DB: explorer
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/postgresql/data
      - type: bind
        source: './psw-be/Razni fajlovi/DEMO_SKRIPTA.sql'
        target: /tmp/DEMO_SKRIPTA.sql
    ports:
      - "5432:5432"

  tour_service:
    build:
      context: ./Tours
      dockerfile: Dockerfile
    image: tours_web_service
    container_name: tours_service
    restart: on-failure
    networks:
      - database
    ports:
      - 8080:8080
    depends_on:
      - database   
      
  blog_service:
    build:
      context: ./Blogs
      dockerfile: Dockerfile
    image: blogs_web_service
    container_name: blogs_service
    restart: on-failure
    networks:
      - database
    ports:
      - 8081:8081
    depends_on:
      - database      

volumes:
  database-data:
    name: explorer

networks:
  database:
    name: database
    driver: bridge    